# Generated by Django 3.2.3 on 2021-06-18 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='longitude',
            new_name='long',
        ),
    ]
