# Generated by Django 3.2.3 on 2021-06-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_remove_address_especificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='especificacion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='t_home',
            field=models.IntegerField(choices=[[0, 'Casa'], [1, 'Edificio'], [2, 'Otro']], null=True, verbose_name='Tipo de Vivienda'),
        ),
    ]
