# Generated by Django 3.2.3 on 2021-06-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20210629_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='address',
            name='especificacion',
        ),
        migrations.AddField(
            model_name='address',
            name='park_address',
            field=models.TextField(null=True, verbose_name='Direccion del Estacionamiento'),
        ),
        migrations.AddField(
            model_name='address',
            name='specification',
            field=models.TextField(null=True, verbose_name='Especificacion del Estacionamiento'),
        ),
    ]
