# Generated by Django 3.2.3 on 2021-06-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20210629_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='available',
            field=models.BooleanField(null=True, verbose_name='Disponible'),
        ),
    ]
