# Generated by Django 3.2.3 on 2021-06-30 00:34

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Numero de Telefono')),
                ('address', models.TextField(max_length=255, verbose_name='Direccion')),
                ('park_address', models.TextField(verbose_name='Direccion del Estacionamiento')),
                ('t_home', models.IntegerField(choices=[[0, 'Casa'], [1, 'Edificio'], [2, 'Otro']], verbose_name='Tipo de Vivienda')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='Numero de Tarjeta')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='Fecha de Expiracion')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='CVV')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
