# Generated by Django 3.2.3 on 2021-06-30 03:07

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Direccion')),
                ('t_home', models.IntegerField(choices=[[0, 'Casa'], [1, 'Edificio'], [2, 'Otro']], verbose_name='Tipo de Vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='CardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25)),
                ('cc_expiry', creditcards.models.CardExpiryField()),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
