# Generated by Django 3.2.3 on 2021-06-30 03:38

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20210629_2307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressInformation',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='cc_code',
            field=creditcards.models.SecurityCodeField(max_length=4, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='cc_expiry',
            field=creditcards.models.CardExpiryField(verbose_name='Fecha de Expiracion'),
        ),
        migrations.AlterField(
            model_name='cardinformation',
            name='cc_number',
            field=creditcards.models.CardNumberField(max_length=25, verbose_name='Numero de Tarjeta'),
        ),
    ]
