# Generated by Django 3.2.3 on 2021-06-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_auto_20210629_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_patent', models.CharField(max_length=10, verbose_name='Placa Patente')),
                ('car_brand', models.CharField(max_length=255, verbose_name='Marca del Auto')),
                ('car_model', models.CharField(max_length=255, verbose_name='Modelo del Auto')),
                ('car_year', models.DateField(verbose_name='Año del Auto')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.carsinformation')),
                ('choose_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.cardinformation')),
            ],
        ),
    ]
