# Generated by Django 3.2.3 on 2021-06-29 18:34

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210629_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=255, verbose_name='Numero de telefono')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=255, verbose_name='Direccion')),
                ('cc_number_client', creditcards.models.CardNumberField(max_length=25, verbose_name='Numero de Tarjeta')),
                ('cc_expiry_client', creditcards.models.CardExpiryField(verbose_name='Fecha de Expiracion')),
                ('cc_code_client', creditcards.models.SecurityCodeField(max_length=4, verbose_name='CVV')),
                ('car_patent', models.CharField(max_length=6, verbose_name='Patente')),
                ('car_brand', models.CharField(max_length=255, verbose_name='Marca')),
                ('car_model', models.CharField(max_length=255, verbose_name='Modelo del Auto')),
                ('car_year', models.DateField()),
                ('car_color', models.CharField(max_length=255, verbose_name='Color del Auto')),
                ('avaible', models.BooleanField()),
            ],
        ),
    ]
