# Generated by Django 3.2.3 on 2021-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='avaible',
        ),
        migrations.AddField(
            model_name='client',
            name='available',
            field=models.BooleanField(null=True, verbose_name='Disponible'),
        ),
    ]
