# Generated by Django 3.2.3 on 2021-06-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210629_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='avaible',
            new_name='available',
        ),
    ]
