# Generated by Django 3.2.3 on 2021-06-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_avaible_client_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='car_year',
            field=models.IntegerField(null=True, verbose_name='Año del Auto'),
        ),
    ]
